# Generated by Django 2.2.6 on 2020-04-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_request_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Matched', 'Matched')], default='Pending', max_length=20),
        ),
    ]
