# Generated by Django 2.2.6 on 2020-04-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200420_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='buyer_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Request'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='property_entry',
        ),
        migrations.AddField(
            model_name='match',
            name='property_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PropertyEntry'),
        ),
    ]
