# Generated by Django 2.2.6 on 2020-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200422_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
