# Generated by Django 2.2.6 on 2020-04-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200422_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='engagement_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
