# Generated by Django 2.2.6 on 2020-04-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200423_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='engagement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
