# Generated by Django 2.2.6 on 2020-04-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200427_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyentry',
            name='property_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
