# Generated by Django 2.2.6 on 2020-04-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200427_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-buyer']},
        ),
    ]
