# Generated by Django 2.2.6 on 2020-05-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200510_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
    ]
