# Generated by Django 2.2.6 on 2020-05-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200510_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyentry',
            name='property_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
