# Generated by Django 2.2.6 on 2020-05-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200511_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-updated_at']},
        ),
    ]
