# Generated by Django 2.2.6 on 2020-05-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20200511_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Property Entries'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
    ]
