# Generated by Django 2.2.6 on 2020-05-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=20, null=True),
        ),
    ]
